metadata:
  metadata_file: 'metadata/metadata_raw.json'
  genres: 'all'
  pct_titles: 10
  overwrite: True
  log_file: 'logs/details.log'
  log_level: 'INFO'
  log_msg_format: '%(asctime)s %(levelname)s %(message)s'
  log_dt_format: '%Y-%m-%d %H:%M:%S'

reviews:
  metadata_file: 'metadata/metadata_raw.json'
  pct_reviews: 100
  overwrite: True
  log_file: 'logs/reviews.log'
  log_level: 'INFO'
  log_msg_format: '%(asctime)s %(levelname)s %(message)s'
  log_dt_format: '%Y-%m-%d %H:%M:%S'  

etl:
  source: 'metadata/metadata.json'
  target: 'metadata/metadata_preprocessed.json'
  reviews_num_partitions: 10
  reviews_partition_format: 'parquet'
